# Generated by Django 4.1.1 on 2022-11-02 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_messages_room_name_alter_group_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='messages',
            table='message',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
