# Generated by Django 4.1.1 on 2022-09-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='username',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='message',
            new_name='content',
        ),
    ]
