# Generated by Django 4.1.1 on 2022-11-09 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_group_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='room_name',
            new_name='group',
        ),
    ]
